export const productList = {
  products: [
    {
      rating: 4.5,
      numReviews: 12,
      price: 89.99,
      available: true,
      _id: "60d55c4cd97a74d6bd80cb22",
      name: "1st Solution Electrical",
      image: "/images/electrical.jpg",
      description:
        "At 1st Solution, we specialize in electrical repair services and troubleshooting for power trips and power failures. Our professional 24/7 electrical contractors are always at your beck and call to maintain, repair & install your electrical appliances & fix all power issues.",
      category: "Electrical",
      user: {
        _id: "60d55c4cd97a74d6bd80cb1f",
        name: "Admin user",
      },
      reviews: [],
      __v: 0,
      createdAt: "2021-06-25T04:32:12.368Z",
      updatedAt: "2021-06-25T04:32:12.368Z",
    },
    {
      rating: 4,
      numReviews: 8,
      price: 599.99,
      available: true,
      _id: "60d55c4cd97a74d6bd80cb23",
      name: "SIN JIT SENG BUILDING",
      image: "/images/home-repair.jpg",
      description:
        "BCA-Approved contractors with over 30 years of experience in the business. We resolve all concrete repair problems and complex leak detection and repairs. WhatsApp, call or fill our contact form for a free quote.",
      category: "Home Renovation",
      user: {
        _id: "60d55c4cd97a74d6bd80cb1f",
        name: "Admin user",
      },
      reviews: [],
      __v: 0,
      createdAt: "2021-06-25T04:32:12.368Z",
      updatedAt: "2021-06-25T04:32:12.368Z",
    },
    {
      rating: 3,
      numReviews: 12,
      price: 929.99,
      available: true,
      _id: "60d55c4cd97a74d6bd80cb24",
      name: "24hrs Shadin Air-conditioning",
      image: "/images/aircon.jpg",
      description:
        "High quality and worry-free air-conditioning services. We provide both commercial and residential solutions",
      category: "Air-conditioning",
      user: {
        _id: "60d55c4cd97a74d6bd80cb1f",
        name: "Admin user",
      },
      reviews: [],
      __v: 0,
      createdAt: "2021-06-25T04:32:12.368Z",
      updatedAt: "2021-06-25T04:32:12.368Z",
    },
    {
      rating: 5,
      numReviews: 12,
      price: 399.99,
      available: true,
      _id: "60d55c4cd97a74d6bd80cb25",
      name: "Plumbing and Sanitary Installation",
      image: "/images/plumbing.jpg",
      description:
        "High quality and worry-free plumbing services. We provide both commercial and residential solutions",
      category: "Plumbing",
      user: {
        _id: "60d55c4cd97a74d6bd80cb1f",
        name: "Admin user",
      },
      reviews: [],
      __v: 0,
      createdAt: "2021-06-25T04:32:12.368Z",
      updatedAt: "2021-06-25T04:32:12.368Z",
    },
    {
      rating: 3.5,
      numReviews: 10,
      price: 49.99,
      available: true,
      _id: "60d55c4cd97a74d6bd80cb26",
      name: "Techbro Computer Services",
      image: "/images/computer.jpg",
      description:
        "We offer reliable, professional and affordable repair services for all of your computer devices, from screen repair replacement, laptop battery replacement, HDD / SSD data recovery and other managed IT maintenance services",
      category: "Computer",
      user: {
        _id: "60d55c4cd97a74d6bd80cb1f",
        name: "Admin user",
      },
      reviews: [],
      __v: 0,
      createdAt: "2021-06-25T04:32:12.368Z",
      updatedAt: "2021-06-25T04:32:12.368Z",
    },
    {
      rating: 4,
      numReviews: 12,
      price: 29.99,
      available: true,
      _id: "60d55c4cd97a74d6bd80cb27",
      name: "Cardilac Plumbing Services",
      image: "/images/plumbing1.jpg",
      description:
        "We provide all sort of Plumbing and Sanitary installation! Plumbing and Sanitary services and repair",
      category: "Plumbing",
      user: {
        _id: "60d55c4cd97a74d6bd80cb1f",
        name: "Admin user",
      },
      reviews: [],
      __v: 0,
      createdAt: "2021-06-25T04:32:12.368Z",
      updatedAt: "2021-06-25T04:32:12.368Z",
    },
    {
      rating: 4,
      numReviews: 12,
      price: 29.99,
      available: true,
      _id: "60d55c4cd97a74d6bd80cb28",
      name: "Lite Mobile",
      image: "/images/mobilerepair.jpg",
      description:
        "Are you looking for the best and most reliable iPhone repairs in Singapore? At Lite Mobile, we got you covered. We understand the inconvenience of having a damaged iPhone. It affects productivity and hinders communication. Our experienced and highly qualified technicians are here to assist you. We offer top-notch iPhone repair services backed with warranty and quality parts. With more convenient service choices and quick, efficient repairs, we value what’s important to you so we don’t waste your time. Servicing iPhone 4/4S to the latest iPhone 12 Pro Max, choose from our comprehensive line-up of iPhone repairs. Lite Mobile specialises in the following iPhone repair services:",
      category: "Mobile",
      user: {
        _id: "60d55c4cd97a74d6bd80cb1f",
        name: "Admin user",
      },
      reviews: [],
      __v: 0,
      createdAt: "2021-06-25T04:32:12.369Z",
      updatedAt: "2021-06-25T04:32:12.369Z",
    },
    {
      rating: 4,
      numReviews: 12,
      price: 29.99,
      available: true,
      _id: "60d55c4cd97a74d6bd80cb29",
      name: "SZ Painting Singapore",
      image: "/images/painting.jpg",
      description:
        "SZ Painting Singapore is committed to providing customers with the best painting services at very affordable prices. You can rely on our experts to provide you with the quality painting services you need. Our painters are locals & truly experienced in interior & exterior painting. We take extra special care of your property, carefully protecting your furniture and non-painted surfaces, and assure you of professional work.",
      category: "Home Renovation",
      user: {
        _id: "60d55c4cd97a74d6bd80cb1f",
        name: "Admin user",
      },
      reviews: [],
      __v: 0,
      createdAt: "2021-06-25T04:32:12.369Z",
      updatedAt: "2021-06-25T04:32:12.369Z",
    },
    {
      rating: 4,
      numReviews: 12,
      price: 29.99,
      available: true,
      _id: "60d55c4cd97a74d6bd80cb2a",
      name: "Aircon Boy",
      image: "/images/aircon1.jpg",
      description:
        "As a company, we do offer long lasting, affordable and high quality repair and installation of air conditioning services which do not malfunction in the short run. Our expertise, experience and capacity are beyond reasonable doubt and we guarantee all our clients with excellent services.",
      category: "Air-conditioning",
      user: {
        _id: "60d55c4cd97a74d6bd80cb1f",
        name: "Admin user",
      },
      reviews: [],
      __v: 0,
      createdAt: "2021-06-25T04:32:12.369Z",
      updatedAt: "2021-06-25T04:32:12.369Z",
    },
  ],
  page: 1,
  pages: 1,
};

export const product = {
  rating: 4.5,
  numReviews: 12,
  price: 89.99,
  available: true,
  _id: "60d55c4cd97a74d6bd80cb22",
  name: "1st Solution Electrical",
  image: "/images/electrical.jpg",
  description:
    "At 1st Solution, we specialize in electrical repair services and troubleshooting for power trips and power failures. Our professional 24/7 electrical contractors are always at your beck and call to maintain, repair & install your electrical appliances & fix all power issues.",
  category: "Electrical",
  user: {
    _id: "60d55c4cd97a74d6bd80cb1f",
    name: "Admin user",
  },
  reviews: [],
  __v: 0,
  createdAt: "2021-06-25T04:32:12.368Z",
  updatedAt: "2021-06-25T04:32:12.368Z",
};

export const createProductStub = {
  rating: 0,
  numReviews: 0,
  price: 89.99,
  available: true,
  _id: "60d79a82a0cad430258efd17",
  user: "60d55c4cd97a74d6bd80cb20",
  name: "2nd Solution Electrical",
  image: "/images/electrical.jpg",
  category: "Electrical",
  description:
    "At 1st Solution, we specialize in electrical repair services and troubleshooting for power trips and power failures. Our professional 24/7 electrical contractors are always at your beck and call to maintain, repair & install your electrical appliances & fix all power issues.",
  reviews: [],
  createdAt: "2021-06-26T21:22:10.234Z",
  updatedAt: "2021-06-26T21:22:10.234Z",
  __v: 0,
};

export const userProducts = [
  {
    rating: 4.5,
    numReviews: 12,
    price: 89.99,
    available: true,
    _id: "60d55c4cd97a74d6bd80cb22",
    name: "1st Solution Electrical",
    image: "/images/electrical.jpg",
    description:
      "At 1st Solution, we specialize in electrical repair services and troubleshooting for power trips and power failures. Our professional 24/7 electrical contractors are always at your beck and call to maintain, repair & install your electrical appliances & fix all power issues.",
    category: "Electrical",
    user: {
      _id: "60d55c4cd97a74d6bd80cb1f",
      name: "Admin user",
    },
    reviews: [],
    __v: 0,
    createdAt: "2021-06-25T04:32:12.368Z",
    updatedAt: "2021-06-25T04:32:12.368Z",
  },
  {
    rating: 4,
    numReviews: 8,
    price: 599.99,
    available: true,
    _id: "60d55c4cd97a74d6bd80cb23",
    name: "SIN JIT SENG BUILDING",
    image: "/images/home-repair.jpg",
    description:
      "BCA-Approved contractors with over 30 years of experience in the business. We resolve all concrete repair problems and complex leak detection and repairs. WhatsApp, call or fill our contact form for a free quote.",
    category: "Home Renovation",
    user: {
      _id: "60d55c4cd97a74d6bd80cb1f",
      name: "Admin user",
    },
    reviews: [],
    __v: 0,
    createdAt: "2021-06-25T04:32:12.368Z",
    updatedAt: "2021-06-25T04:32:12.368Z",
  },
  {
    rating: 3,
    numReviews: 12,
    price: 929.99,
    available: true,
    _id: "60d55c4cd97a74d6bd80cb24",
    name: "24hrs Shadin Air-conditioning",
    image: "/images/aircon.jpg",
    description:
      "High quality and worry-free air-conditioning services. We provide both commercial and residential solutions",
    category: "Air-conditioning",
    user: {
      _id: "60d55c4cd97a74d6bd80cb1f",
      name: "Admin user",
    },
    reviews: [],
    __v: 0,
    createdAt: "2021-06-25T04:32:12.368Z",
    updatedAt: "2021-06-25T04:32:12.368Z",
  },
  {
    rating: 5,
    numReviews: 12,
    price: 399.99,
    available: true,
    _id: "60d55c4cd97a74d6bd80cb25",
    name: "Plumbing and Sanitary Installation",
    image: "/images/plumbing.jpg",
    description:
      "High quality and worry-free plumbing services. We provide both commercial and residential solutions",
    category: "Plumbing",
    user: {
      _id: "60d55c4cd97a74d6bd80cb1f",
      name: "Admin user",
    },
    reviews: [],
    __v: 0,
    createdAt: "2021-06-25T04:32:12.368Z",
    updatedAt: "2021-06-25T04:32:12.368Z",
  },
  {
    rating: 3.5,
    numReviews: 10,
    price: 49.99,
    available: true,
    _id: "60d55c4cd97a74d6bd80cb26",
    name: "Techbro Computer Services",
    image: "/images/computer.jpg",
    description:
      "We offer reliable, professional and affordable repair services for all of your computer devices, from screen repair replacement, laptop battery replacement, HDD / SSD data recovery and other managed IT maintenance services",
    category: "Computer",
    user: {
      _id: "60d55c4cd97a74d6bd80cb1f",
      name: "Admin user",
    },
    reviews: [],
    __v: 0,
    createdAt: "2021-06-25T04:32:12.368Z",
    updatedAt: "2021-06-25T04:32:12.368Z",
  },
  {
    rating: 4,
    numReviews: 12,
    price: 29.99,
    available: true,
    _id: "60d55c4cd97a74d6bd80cb27",
    name: "Cardilac Plumbing Services",
    image: "/images/plumbing1.jpg",
    description:
      "We provide all sort of Plumbing and Sanitary installation! Plumbing and Sanitary services and repair",
    category: "Plumbing",
    user: {
      _id: "60d55c4cd97a74d6bd80cb1f",
      name: "Admin user",
    },
    reviews: [],
    __v: 0,
    createdAt: "2021-06-25T04:32:12.368Z",
    updatedAt: "2021-06-25T04:32:12.368Z",
  },
  {
    rating: 4,
    numReviews: 12,
    price: 29.99,
    available: true,
    _id: "60d55c4cd97a74d6bd80cb28",
    name: "Lite Mobile",
    image: "/images/mobilerepair.jpg",
    description:
      "Are you looking for the best and most reliable iPhone repairs in Singapore? At Lite Mobile, we got you covered. We understand the inconvenience of having a damaged iPhone. It affects productivity and hinders communication. Our experienced and highly qualified technicians are here to assist you. We offer top-notch iPhone repair services backed with warranty and quality parts. With more convenient service choices and quick, efficient repairs, we value what’s important to you so we don’t waste your time. Servicing iPhone 4/4S to the latest iPhone 12 Pro Max, choose from our comprehensive line-up of iPhone repairs. Lite Mobile specialises in the following iPhone repair services:",
    category: "Mobile",
    user: {
      _id: "60d55c4cd97a74d6bd80cb1f",
      name: "Admin user",
    },
    reviews: [],
    __v: 0,
    createdAt: "2021-06-25T04:32:12.369Z",
    updatedAt: "2021-06-25T04:32:12.369Z",
  },
  {
    rating: 4,
    numReviews: 12,
    price: 29.99,
    available: true,
    _id: "60d55c4cd97a74d6bd80cb29",
    name: "SZ Painting Singapore",
    image: "/images/painting.jpg",
    description:
      "SZ Painting Singapore is committed to providing customers with the best painting services at very affordable prices. You can rely on our experts to provide you with the quality painting services you need. Our painters are locals & truly experienced in interior & exterior painting. We take extra special care of your property, carefully protecting your furniture and non-painted surfaces, and assure you of professional work.",
    category: "Home Renovation",
    user: {
      _id: "60d55c4cd97a74d6bd80cb1f",
      name: "Admin user",
    },
    reviews: [],
    __v: 0,
    createdAt: "2021-06-25T04:32:12.369Z",
    updatedAt: "2021-06-25T04:32:12.369Z",
  },
  {
    rating: 4,
    numReviews: 12,
    price: 29.99,
    available: true,
    _id: "60d55c4cd97a74d6bd80cb2a",
    name: "Aircon Boy",
    image: "/images/aircon1.jpg",
    description:
      "As a company, we do offer long lasting, affordable and high quality repair and installation of air conditioning services which do not malfunction in the short run. Our expertise, experience and capacity are beyond reasonable doubt and we guarantee all our clients with excellent services.",
    category: "Air-conditioning",
    user: {
      _id: "60d55c4cd97a74d6bd80cb1f",
      name: "Admin user",
    },
    reviews: [],
    __v: 0,
    createdAt: "2021-06-25T04:32:12.369Z",
    updatedAt: "2021-06-25T04:32:12.369Z",
  },
];
