export const CERT_LIST_REQUEST = "CERT_LIST_REQUEST"
export const CERT_LIST_SUCCESS = "CERT_LIST_SUCCESS"
export const CERT_LIST_FAIL = "CERT_LIST_FAIL"

export const CERT_DETAILS_REQUEST = "CERT_DETAILS_REQUEST"
export const CERT_DETAILS_SUCCESS = "CERT_DETAILS_SUCCESS"
export const CERT_DETAILS_FAIL = "CERT_DETAILS_FAIL"
export const CERT_DETAILS_RESET = "CERT_DETAILS_RESET"

export const CERT_DELETE_REQUEST = "CERT_DELETE_REQUEST"
export const CERT_DELETE_SUCCESS = "CERT_DELETE_SUCCESS"
export const CERT_DELETE_FAIL = "CERT_DELETE_FAIL"
export const CERT_DELETE_RESET = "CERT_DELETE_RESET"

export const CERT_CREATE_REQUEST = "CERT_CREATE_REQUEST"
export const CERT_CREATE_SUCCESS = "CERT_CREATE_SUCCESS"
export const CERT_CREATE_FAIL = "CERT_CREATE_FAIL"
export const CERT_CREATE_RESET = "CERT_CREATE_RESET"

export const CERT_UPDATE_REQUEST = "CERT_UPDATE_REQUEST"
export const CERT_UPDATE_SUCCESS = "CERT_UPDATE_SUCCESS"
export const CERT_UPDATE_FAIL = "CERT_UPDATE_FAIL"
export const CERT_UPDATE_RESET = "CERT_UPDATE_RESET"

export const CERT_LIST_USER_REQUEST = "CERT_LIST_USER_REQUEST"
export const CERT_LIST_USER_SUCCESS = "CERT_LIST_USER_SUCCESS"
export const CERT_LIST_USER_FAIL = "CERT_LIST_USER_FAIL"
export const CERT_LIST_USER_RESET = "CERT_LIST_USER_RESET"
