export const OFFER_CREATE_REQUEST = 'OFFER_CREATE_REQUEST'
export const OFFER_CREATE_SUCCESS = 'OFFER_CREATE_SUCCESS'
export const OFFER_CREATE_FAIL = 'OFFER_CREATE_FAIL'
export const OFFER_CREATE_RESET = 'OFFER_CREATE_RESET'

export const OFFER_LIST_REQUEST = 'OFFER_LIST_REQUEST'
export const OFFER_LIST_SUCCESS = 'OFFER_LIST_SUCCESS'
export const OFFER_LIST_FAIL = 'OFFER_LIST_FAIL'
export const OFFER_LIST_RESET = 'OFFER_LIST_RESET'

export const OFFER_ACCEPT_REQUEST = 'OFFER_ACCEPT_REQUEST'
export const OFFER_ACCEPT_SUCCESS = 'OFFER_ACCEPT_SUCCESS'
export const OFFER_ACCEPT_FAIL = 'OFFER_ACCEPT_FAIL'
export const OFFER_ACCEPT_RESET = 'OFFER_ACCEPT_RESET'

export const OFFER_REJECT_REQUEST = 'OFFER_REJECT_REQUEST'
export const OFFER_REJECT_SUCCESS = 'OFFER_REJECT_SUCCESS'
export const OFFER_REJECT_FAIL = 'OFFER_REJECT_FAIL'
export const OFFER_REJECT_RESET = 'OFFER_REJECT_RESET'

export const OFFER_PRICE_UPDATE_REQUEST = 'OFFER_PRICE_UPDATE_REQUEST'
export const OFFER_PRICE_UPDATE_SUCCESS = 'OFFER_PRICE_UPDATE_SUCCESS'
export const OFFER_PRICE_UPDATE_FAIL = 'OFFER_PRICE_UPDATE_FAIL'
export const OFFER_PRICE_UPDATE_RESET = 'OFFER_PRICE_UPDATE_RESET'
